### ISSUE TITLE
Add new quiz

### ISSUE THREAD

**Issue by saman1357** [neuefische/cgn-java-23-2-teamproject-quiz#10]
# User story
As a user, I want to add new quizzes, so I can have more quizzes to play

# Acceptance criteria

- [ ] you can type a question and an answer to create a new quiz.

# Tasks
- [x] create add Method in QuizRepo
- [x] create add Method in QuizService
- [x] create post endpoint in QuizController
- [x] write unit and integration tests
- [x] create input form to send inputs to backend
