### ISSUE TITLE
Update Quiz Card

### ISSUE THREAD

**Issue by sirtobiwan** [neuefische/cgn-java-23-2-teamproject-quiz#12]
# User story
As a user, I want to change a quiz card, so I can update its question/answer.

# Acceptance criteria

- [ ] Display a button do edit the quiz card

# Task
- [ ] Put-Controller
- [ ] Quiz Service Method
- [ ] Quiz Repo Method
- [ ] Unit/Integration Test
- [ ] Frontend Input + Edit Button
