### ISSUE TITLE
Delete Quiz Card

### ISSUE THREAD

**Issue by sirtobiwan** [neuefische/cgn-java-23-2-teamproject-quiz#13]
# User story
As a user, I want to delete a quiz card, so I can remove it from the list.

# Acceptance criteria

- [ ] Display a button do delete the quiz card

# Task
- [ ] Delete-Controller
- [ ] Quiz Service Method
- [ ] Quiz Repo Method
- [ ] Unit/Integration Test
- [ ] Frontend Delete Button
