### ISSUE TITLE
Styling with CSS and MUI

### ISSUE THREAD

**Issue by sahedw** [neuefische/cgn-java-23-2-teamproject-quiz#17]
# User story
As a user I want to have a visually appealing site so that I can have fun with it and feel good using it

# Acceptance criteria

- [x] The website looks clean and structured

# Task
- [x] Design Form Component
- [x] Design QuizCard
- [x] Maybe structure site with react router
